markdown: kramdown
exclude:
  - LICENSE
  - Makefile
  - README
markdown_ext: "md"

layouts_dir: ./_noita
baseurl: /85309
piazza: piazza.com/cmu/spring2021/85309/home
openintro: post/intro-randomization.pdf
teams:

plugins:
  - jemoji

noita:
  name: 85-309 - Statistical Methods and Concepts for Social and Behavioral Sciences
  description: 85-309 - Statistical Methods and Concepts
  author:
    name: Dan Yurovsky
    url: http://callab.github.io
    absolute: true
  lang: en
  topbar:
    toggle: Menu
    right:
      - name: Schedule
        url: /
      - name: Info
        url: /info/
      - name: Syllabus
        url: /syllabus/
      - name: Piazza
        url: piazza.com/cmu/spring2021/85309/home
        absolute: true
